import Navigation from "../components/Navigation"
import Head from 'next/head'
import Phrase from "../components/phrase/Phrase"
import 'bootstrap/dist/css/bootstrap.min.css';
import LoginPage from "./LoginPage";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import { Container } from "react-bootstrap";

export default function Home() {

  const {data: session, status} = useSession();

  const storeUser = async () => {
    return fetch("/api/auth/storeuser")
  }

  useEffect(() => {
      storeUser()
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation></Navigation>
        <br />
        <div style={{display: "flex", flexDirection: "row", flexWrap: "wrap", padding: "0.3em", height: "auto", width: "100%", margin: 0}}>
          { status === "unauthenticated" ? <LoginPage /> : <Phrase />}
        </div>
      </main>
    </>
  )
}
