import Navigation from "../components/Navigation"
import Head from 'next/head'
import Image from 'next/image'
import Phrase from "../components/phrase/Phrase"
import 'bootstrap/dist/css/bootstrap.min.css';
import LoginPage from "./LoginPage";
import { useSession } from "next-auth/react";

export default function Home() {

  const {data: session, status} = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation></Navigation>
        <br />
        <div style={{display: "flex", flexDirection: "row", flexWrap: "wrap", padding: "0.3em"}}>
          { status === "unauthenticated" ? <LoginPage /> : <Phrase />}
        </div>
      </main>
    </>
  )
}
